server:
  port: 8085

spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
